export const RATE_PROVIDER = Symbol('RATE_PROVIDER');
export const MONOBANK_PROVIDER_OPTIONS = Symbol('MONOBANK_PROVIDER_OPTIONS');
export const RATES_REPOSITORY = Symbol('RATES_REPOSITORY');
export const RATES_CACHE_OPTIONS = Symbol('RATES_CACHE_OPTIONS');
